version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6379:6379"
    networks:
      - property_network

volumes:
  postgres_data:

networks:
  property_network:
    driver: bridge
